// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/ratelimiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // who is making the request
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`       // which rule to apply (e.g. "login", "search")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLimitRequest) Reset() {
	*x = CheckLimitRequest{}
	mi := &file_proto_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitRequest) ProtoMessage() {}

func (x *CheckLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLimitRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckLimitRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type CheckLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                                 // should the caller proceed?
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`                             // how many requests left in window
	RetryAfterMs  int64                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // if blocked, wait this long before retrying
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                              // which algorithm handled this (for observability)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLimitResponse) Reset() {
	*x = CheckLimitResponse{}
	mi := &file_proto_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitResponse) ProtoMessage() {}

func (x *CheckLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *CheckLimitResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

var File_proto_ratelimiter_proto protoreflect.FileDescriptor

const file_proto_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ratelimiter.proto\x12\vratelimiter\"I\n" +
	"\x11CheckLimitRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\"\x90\x01\n" +
	"\x12CheckLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm2\\\n" +
	"\vRateLimiter\x12M\n" +
	"\n" +
	"CheckLimit\x12\x1e.ratelimiter.CheckLimitRequest\x1a\x1f.ratelimiter.CheckLimitResponseB\x1fZ\x1dgithub.com/cynkin/rlaas/protob\x06proto3"

var (
	file_proto_ratelimiter_proto_rawDescOnce sync.Once
	file_proto_ratelimiter_proto_rawDescData []byte
)

func file_proto_ratelimiter_proto_rawDescGZIP() []byte {
	file_proto_ratelimiter_proto_rawDescOnce.Do(func() {
		file_proto_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimiter_proto_rawDesc), len(file_proto_ratelimiter_proto_rawDesc)))
	})
	return file_proto_ratelimiter_proto_rawDescData
}

var file_proto_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ratelimiter_proto_goTypes = []any{
	(*CheckLimitRequest)(nil),  // 0: ratelimiter.CheckLimitRequest
	(*CheckLimitResponse)(nil), // 1: ratelimiter.CheckLimitResponse
}
var file_proto_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.RateLimiter.CheckLimit:input_type -> ratelimiter.CheckLimitRequest
	1, // 1: ratelimiter.RateLimiter.CheckLimit:output_type -> ratelimiter.CheckLimitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimiter_proto_init() }
func file_proto_ratelimiter_proto_init() {
	if File_proto_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimiter_proto_rawDesc), len(file_proto_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimiter_proto_goTypes,
		DependencyIndexes: file_proto_ratelimiter_proto_depIdxs,
		MessageInfos:      file_proto_ratelimiter_proto_msgTypes,
	}.Build()
	File_proto_ratelimiter_proto = out.File
	file_proto_ratelimiter_proto_goTypes = nil
	file_proto_ratelimiter_proto_depIdxs = nil
}
